### ISSUE TITLE
The font color and background are both white

### ISSUE THREAD

**Issue by fineart01** [Akmadan23/gscal#1]
the line 216 of main.py is " fg = "white"", the app window background is white too, so i can see nothing in the window. so i modify it with "fg= "black", then it work fine.

**Comment by Akmadan23** [comment]
I see, that's because I only tested it with a dark theme so I didn't noticed the issue. I'm already looking for a solution involving colors of the gtk theme in use, so that it should work whether it's a dark or a light theme.

**Comment by Akmadan23** [comment]
Now it should work fine with any gtk theme, the new release has just been uploaded to PyPI and the AUR. Let me know if it works for you now.
